<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CountryCode;

class CountryCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CountryCode::truncate();
  
        $country_codes = [
            ['name' => 'India (+91)', 'country_code' =>'+91' ,'code' => 'IN'],
            ['name' => 'Afghanistan (+93)', 'country_code' =>'+93' ,'code' => 'AF'],
            ['name' => 'Åland Islands (+358)', 'country_code' =>'+358' , 'code' => 'AX'],
            ['name' => 'Albania (+355)', 'country_code' =>'+355' ,'code' => 'AL'],
            ['name' => 'Algeria (+213)', 'country_code' =>'+213' ,'code' => 'DZ'],
            ['name' => 'American Samoa (+1)', 'country_code' =>'+1' ,'code' => 'AS'],
            ['name' => 'Andorra (+376)', 'country_code' =>'+376' ,'code' => 'AD'],
            ['name' => 'Angola (+244)','country_code' =>'+244' , 'code' => 'AO'],
            ['name' => 'Anguilla (+1)', 'country_code' =>'+1' ,'code' => 'AI'],
            ['name' => 'Antigua Barbuda (+1)','country_code' =>'+1' , 'code' => 'AG'],
            ['name' => 'Argentina (+54)', 'country_code' =>'+54' ,'code' => 'AR'],
            ['name' => 'Armenia (+374)','country_code' =>'+374' , 'code' => 'AM'],
            ['name' => 'Aruba (+297)','country_code' =>'+297' , 'code' => 'AW'],
            ['name' => 'Australia (+61)', 'country_code' =>'+61' ,'code' => 'AU'],
            ['name' => 'Austria (+43)', 'country_code' =>'+43' ,'code' => 'AT'],
            ['name' => 'Azerbaijan (+994)', 'country_code' =>'+994' ,'code' => 'AZ'],
            ['name' => 'Bahamas (+1)','country_code' =>'+1' , 'code' => 'BS'],
            ['name' => 'Bahrain (+973)', 'country_code' =>'+973' ,'code' => 'BH'],
            ['name' => 'Bangladesh (+880)', 'country_code' =>'+880' ,'code' => 'BD'],
            ['name' => 'Barbados (+1)', 'country_code' =>'+1' ,'code' => 'BB'],
            ['name' => 'Belarus (+375)','country_code' =>'+375' , 'code' => 'BY'],
            ['name' => 'Belgium (+32)', 'country_code' =>'+32' ,'code' => 'BE'],
            ['name' => 'Belize (+501)', 'country_code' =>'+501' ,'code' => 'BZ'],
            ['name' => 'Benin (+229)', 'country_code' =>'+229' ,'code' => 'BJ'],
            ['name' => 'Bermuda (+1)','country_code' =>'+1' , 'code' => 'BM'],
            ['name' => 'Bhutan (+975)', 'country_code' =>'+975' ,'code' => 'BT'],
            ['name' => 'Bolivia (+591)','country_code' =>'+591' , 'code' => 'BO'],
            ['name' => 'Bosnia Herzegovina (+387)', 'country_code' =>'+387' ,'code' => 'BA'],
            ['name' => 'Botswana (+267)','country_code' =>'+267' , 'code' => 'BW'],
            ['name' => 'Brazil (+55)','country_code' =>'+55' , 'code' => 'BR'],
            ['name' => 'British Indian Ocean Territory (+246)','country_code' =>'+246' , 'code' => 'IO'],
            ['name' => 'British Virgin Islands (+1)','country_code' =>'+1' , 'code' => 'VG'],
            ['name' => 'Brunei (+673)','country_code' =>'+673' , 'code' => 'BN'],
            ['name' => 'Bulgaria (+359)', 'country_code' =>'+359' ,'code' => 'BG'],
            ['name' => 'Burkina Faso (+226)','country_code' =>'+226' , 'code' => 'BF'],
            ['name' => 'Burundi (+257)', 'country_code' =>'+257' ,'code' => 'BI'],
            ['name' => 'Cambodia (+855)', 'country_code' =>'+855' ,'code' => 'KH'],
            ['name' => 'Cameroon (+237)','country_code' =>'+237' , 'code' => 'CM'],
            ['name' => 'Canada (+1)','country_code' =>'+1' , 'code' => 'CA'],
            ['name' => 'Cape Verde (+238)', 'country_code' =>'+238' ,'code' => 'CV'],
            ['name' => 'Caribbean Netherlands (+599)', 'country_code' =>'+599' ,'code' => 'BQ'],
            ['name' => 'Cayman Islands (+1)','country_code' =>'+1' , 'code' => 'KY'],
            ['name' => 'Central African Republic (+236)','country_code' =>'+236' , 'code' => 'CF'],
            ['name' => 'Chad (+235)','country_code' =>'+235' , 'code' => 'TD'],
            ['name' => 'Chile (+56)','country_code' =>'+56' , 'code' => 'CL'],
            ['name' => 'China (+86)','country_code' =>'+86' , 'code' => 'CN'],
            ['name' => 'Christmas Island (+61)', 'country_code' =>'+61' ,'code' => 'CX'],
            ['name' => 'Cocos (Keeling) Islands (+61)', 'country_code' =>'+61' ,'code' => 'CC'],
            ['name' => 'Colombia (+57)','country_code' =>'+57' , 'code' => 'CO'],
            ['name' => 'Comoros (+269)','country_code' =>'+269' , 'code' => 'KM'],
            ['name' => 'Congo - Brazzaville (+242)','country_code' =>'+242' ,'code' => 'CG'],
            ['name' => 'Congo - Kinshasa (+243)','country_code' =>'+243' , 'code' => 'CD'],
            ['name' => 'Cook Islands (+682)','country_code' =>'+682' , 'code' => 'CK'],
            ['name' => 'Costa Rica (+506)','country_code' =>'+506' , 'code' => 'CR'],
            ['name' => 'Côte d’Ivoire (+225)', 'country_code' =>'+225' ,'code' => 'CI'],
            ['name' => 'Croatia (+385)', 'country_code' =>'+385' ,'code' => 'HR'],
            ['name' => 'Cuba (+53)','country_code' =>'+53' , 'code' => 'CU'],
            ['name' => 'Curaçao (+599)', 'country_code' =>'+599' ,'code' => 'CW'],
            ['name' => 'Cyprus (+357)', 'country_code' =>'+357' ,'code' => 'CY'],
            ['name' => 'Czechia (+420)','country_code' =>'+420' , 'code' => 'CZ'],
            ['name' => 'Denmark (+45)', 'country_code' =>'+45' ,'code' => 'DK'],
            ['name' => 'Djibouti (+253)', 'country_code' =>'+253' ,'code' => 'DJ'],
            ['name' => 'Dominica (+1)', 'country_code' =>'+1' ,'code' => 'DM'],
            ['name' => 'Dominican Republic (+1)', 'country_code' =>'+1' ,'code' => 'DO'],
            ['name' => 'Ecuador (+593)', 'country_code' =>'+593' ,'code' => 'EC'],
            ['name' => 'Egypt (+20)', 'country_code' =>'+20' ,'code' => 'EG'],
            ['name' => 'El Salvador (+503)', 'country_code' =>'+503' ,'code' => 'SV'],
            ['name' => 'Equatorial Guinea (+240)','country_code' =>'+240' , 'code' => 'GQ'],
            ['name' => 'Eritrea (+291)', 'country_code' =>'+291' ,'code' => 'ER'],
            ['name' => 'Estonia (+372)','country_code' =>'+372' , 'code' => 'EE'],
            ['name' => 'Eswatini (+268)','country_code' =>'+268' , 'code' => 'SZ'],
            ['name' => 'Ethiopia (+251)','country_code' =>'+251' , 'code' => 'ET'],
            ['name' => 'Falkland Islands (+500)', 'country_code' =>'+500' ,'code' => 'FK'],
            ['name' => 'Faroe Islands (+298)', 'country_code' =>'+298' ,'code' => 'FO'],
            ['name' => 'Fiji (+679)','country_code' =>'+679' , 'code' => 'FJ'],
            ['name' => 'Finland (+358)', 'country_code' =>'+358' ,'code' => 'FI'],
            ['name' => 'France (+33)', 'country_code' =>'+33' ,'code' => 'FR'],
            ['name' => 'French Guiana (+594)', 'country_code' =>'+594' ,'code' => 'GF'],
            ['name' => 'French Polynesia (+689)', 'country_code' =>'+689' ,'code' => 'PF'],
            ['name' => 'Gabon (+241)', 'country_code' =>'+241' ,'code' => 'GA'],
            ['name' => 'Gambia (+220)', 'country_code' =>'+220' ,'code' => 'GM'],
            ['name' =>'Georgia (+995)','country_code' =>'+233' ,'code' => 'GH'],
            ['name' =>'Gibraltar (+350)', 'country_code' =>'+350' ,'code' => 'GI'],
            ['name' =>'Greece (+30)', 'country_code' =>'+30' ,'code' => 'GR'],
            ['name' =>'Greenland (+299)','country_code' =>'+299' , 'code' => 'GL'],
            ['name' =>'Grenada (+1)','country_code' =>'+1' , 'code' => 'GD'],
            ['name' =>'Guadeloupe (+590)','country_code' =>'+590' , 'code' => 'GP'],
            ['name' =>'Guam (+1)', 'country_code' =>'+1' ,'code' => 'GU'],
            ['name' =>'Guatemala (+502)','country_code' =>'+502' , 'code' => 'GT'],
            ['name' =>'Guernsey (+44)' , 'country_code' =>'+44' ,'code' =>'GG'],
            ['name' =>'Guinea (+224)' , 'country_code' =>'+224' ,'code' =>'GN'],
            ['name' =>'Guinea-Bissau (+245)' ,'country_code' =>'+245' , 'code' =>'GW'],
            ['name' =>'Guyana (+592)' ,'country_code' =>'+592' , 'code' =>'GY'],
            ['name' =>'Haiti (+509)' ,'country_code' =>'+509' , 'code' =>'HT'],
            ['name' =>'Honduras (+504)' , 'country_code' =>'+504' ,'code' =>'HN'],
            ['name' =>'Hong Kong SAR China (+852)' , 'country_code' =>'+852' ,'code' =>'HK'],
            ['name' =>'Hungary (+36)' ,'country_code' =>'+36' , 'code' =>'HU'],
            ['name' =>'Iceland (+354)' , 'country_code' =>'+354' ,'code' =>'IS'],
            ['name' =>'India (+91)' , 'country_code' =>'+91' ,'code' =>'IN'],
            ['name' =>'Indonesia (+62)' , 'country_code' =>'+62' ,'code' =>'ID'],
            ['name' =>'Iran (+98)' , 'country_code' =>'+98' ,'code' =>'IR'],
            ['name' =>'Iraq (+964)' ,'country_code' =>'+964' , 'code' =>'IQ'],
            ['name' =>'Ireland (+353)' ,'country_code' =>'+353' , 'code' =>'IE'],
            ['name' =>'Isle of Man (+44)' , 'country_code' =>'+44' ,'code' =>'IM'],
            ['name' =>'Israel (+972)' ,'country_code' =>'+972' , 'code' => 'IL'],
            ['name' =>'Italy (+39)' ,'country_code' =>'+39' , 'code' => 'IT'],
            ['name' =>'Jamaica (+1)' ,'country_code' =>'+1' , 'code' => 'JM'],
            ['name' =>'Japan (+81)' ,'country_code' =>'+81' , 'code' => 'JP'],
            ['name' =>'Jersey (+44)' ,'country_code' =>'+44' , 'code' => 'JE'],
            ['name' =>'Jordan (+962)' ,'country_code' =>'+962' , 'code' => 'JO'],
            ['name' =>'Kazakhstan (+7)' , 'country_code' =>'+7' ,'code' => 'KZ'],
            ['name' =>'Kenya (+254)' ,'country_code' =>'+254' , 'code' => 'KE'],
            ['name' =>'Kiribati (+686)' , 'country_code' =>'+686' ,'code' => 'KI'],
            ['name' =>'Kuwait (+965)' , 'country_code' =>'+965' ,'code' => 'KW'],
            ['name' =>'Kyrgyzstan (+996)' , 'country_code' =>'+996' ,'code' => 'KG'],
            ['name' =>'Laos (+856)' ,'country_code' =>'+856' , 'code' => 'LA'],
            ['name' =>'Latvia (+371)' ,'country_code' =>'+371' , 'code' => 'LV'],
            ['name' =>'Lebanon (+961)' ,'country_code' =>'+961' , 'code' => 'LB'],
            ['name' =>'Lesotho (+266)' ,'country_code' =>'+266' , 'code' => 'LS'],
            ['name' =>'Liberia (+231)' , 'country_code' =>'+231' ,'code' => 'LR'],
            ['name' => 'Libya (+218)' , 'country_code' =>'+218' ,'code' => 'LY'],
            ['name' => 'Liechtenstein (+423)' , 'country_code' =>'+432' ,'code' => 'LI'],
            ['name' => 'Lithuania (+370)' ,'country_code' =>'+370' , 'code' => 'LT'],
            ['name' => 'Luxembourg (+352)' ,'country_code' =>'+352' , 'code' => 'LU'],
            ['name' => 'Macao SAR China (+853)' ,'country_code' =>'+853' , 'code' => 'MO'],
            ['name' => 'Madagascar (+261)' ,'country_code' =>'+261' , 'code' => 'MG'],
            ['name' => 'Malawi (+265)' , 'country_code' =>'+265' ,'code' => 'MW'],
            ['name' => 'Malaysia (+60)' , 'country_code' =>'+60' ,'code' => 'MY'],
            ['name' => 'Maldives (+960)' , 'country_code' =>'+960' ,'code' => 'MV'],
            ['name' => 'Mali (+223)' ,'country_code' =>'+223' , 'code' => 'ML'],
            ['name' => 'Malta (+356)' , 'country_code' =>'+356' ,'code' => 'MT'],
            ['name' => 'Marshall Islands (+692)' ,'country_code' =>'+692' , 'code' => 'MH'],
            ['name' => 'Martinique (+596)' ,'country_code' =>'+596' , 'code' => 'MQ'],
            ['name' => 'Mauritania (+222)' ,'country_code' =>'+222' , 'code' => 'MR'],
            ['name' => 'Mauritius (+230)' ,'country_code' =>'+230' , 'code' => 'MU'],
            ['name' => 'Mayotte (+262)' ,'country_code' =>'+262' , 'code' => 'YT'],
            ['name' => 'Mexico (+52)' ,'country_code' =>'+52' , 'code' => 'MX'],
            ['name' => 'Micronesia (+691)' , 'country_code' =>'+691' ,'code' => 'FM'],
            ['name' => 'Moldova (+373)' , 'country_code' =>'+373' ,'code' => 'MD'],
            ['name' => 'Monaco (+377)' , 'country_code' =>'+377' ,'code' => 'MC'],
            ['name' => 'Mongolia (+976)' , 'country_code' =>'+976' ,'code' => 'MN'],
            ['name' => 'Montenegro (+382)' , 'country_code' =>'+382' ,'code' => 'ME'],
            ['name' => 'Montserrat (+1)' ,'country_code' =>'+1' , 'code' => 'MS'],
            ['name' => 'Morocco (+212)' , 'country_code' =>'+212' ,'code' => 'MA'],
            ['name' => 'Mozambique (+258)' ,'country_code' =>'+258' , 'code' => 'MZ'],
            ['name' => 'Myanmar (Burma) (+95)' ,'country_code' =>'+95' , 'code' => 'MM'],
            ['name' => 'Namibia (+264)' ,'country_code' =>'+264' , 'code' => 'NA'],
            ['name' => 'Nauru (+674)' , 'country_code' =>'+674' ,'code' => 'NR'],
            ['name' => 'Nepal (+977)' ,'country_code' =>'+977' , 'code' => 'NP'],
            ['name' => 'Netherlands (+31)' ,'country_code' =>'+31' , 'code' => 'NL'],
            ['name' => 'New Caledonia (+687)' , 'country_code' =>'+687' ,'code' => 'NC'],
            ['name' => 'New Zealand (+64)' , 'country_code' =>'+64' ,'code' => 'NZ'],
            ['name' => 'Nicaragua (+505)' ,'country_code' =>'+505' , 'code' => 'NI'],
            ['name' => 'Niger (+227)' , 'country_code' =>'+227' ,'code' => 'NE'],
            ['name' => 'Nigeria (+234)' , 'country_code' =>'+234' ,'code' => 'NG'],
            ['name' => 'Niue (+683)' , 'country_code' =>'+683' ,'code' => 'NU'],
            ['name' => 'Norfolk Island (+672)' , 'country_code' =>'+672' ,'code' => 'F'],
            ['name' => 'North Korea (+850)' ,'country_code' =>'+850' , 'code' => 'KP'],
            ['name' => 'North Macedonia (+389)' ,'country_code' =>'+389' , 'code' => 'MK'],
            ['name' => 'Northern Mariana Islands (+1)' , 'country_code' =>'+1' ,'code' => 'MP'],
            ['name' => 'Norway (+47)' , 'country_code' =>'+47' ,'code' => 'NO'],
            ['name' => 'Oman (+968)', 'country_code' =>'+968' ,'code' => 'OM'],
            ['name' => 'Pakistan (+92)' ,'country_code' =>'+92' , 'code' => 'PK'],
            ['name' => 'Palau (+680)' , 'country_code' =>'+680' ,'code' => 'PW'],
            ['name' => 'Palestinian Territories (+970)' ,'country_code' =>'+970' , 'code' => 'PS'],
            ['name' => 'Panama (+507)' , 'country_code' =>'+507' ,'code' => 'PA'],
            ['name' => 'Papua New Guinea (+675)' ,'country_code' =>'+675' , 'code' => 'PG'],
            ['name' => 'Paraguay (+595)' , 'country_code' =>'+595' ,'code' => 'PY'],
            ['name' => 'Peru (+51)' , 'country_code' =>'+51' ,'code' => 'PE'],
            ['name' => 'Philippines (+63)', 'country_code' =>'+63' ,'code' => 'PH'],
            ['name' => 'Poland (+48)','country_code' =>'+48' , 'code' => 'PL'],
            ['name' => 'Portugal (+351)', 'country_code' =>'+351' ,'code' => 'PT'],
            ['name' => 'Puerto Rico (+1)','country_code' =>'+1' , 'code' => 'PR'],
            ['name' => 'Qatar (+974)', 'country_code' =>'+974' ,'code' => 'QA'],
            ['name' => 'Réunion (+262)', 'country_code' =>'+262' ,'code' => 'RE'],
            ['name' => 'Romania (+40)', 'country_code' =>'+40' ,'code' => 'RO'],
            ['name' => 'Russia (+7)','country_code' =>'+7' , 'code' => 'RU'],
            ['name' => 'Rwanda (+250)', 'country_code' =>'+250' ,'code' => 'RW'],
            ['name' => 'Samoa (+685)','country_code' =>'+685' , 'code' => 'WS'],
            ['name' => 'San Marino (+378)', 'country_code' =>'+378' ,'code' => 'SM'],
            ['name' => 'São Tomé &amp; Príncipe (+239)', 'country_code' =>'+239' ,'code' => 'ST'],
            ['name' => 'Saudi Arabia (+966)', 'country_code' =>'+966' ,'code' => 'SA'],
            ['name' => 'Senegal (+221)', 'country_code' =>'+221' ,'code' => 'SN'],
            ['name' => 'Serbia (+381)','country_code' =>'+381' , 'code' => 'RS'],
            ['name' => 'Seychelles (+248)','country_code' =>'+248' , 'code' => 'SC'],
            ['name' => 'Sierra Leone (+232)', 'country_code' =>'+232' ,'code' => 'SL'],
            ['name' => 'Singapore (+65)','country_code' =>'+65' , 'code' => 'SG'],
            ['name' => 'Sint Maarten (+1)', 'country_code' =>'+1' ,'code' => 'SX'],
            ['name' => 'Slovakia (+421)','country_code' =>'+421' , 'code' => 'SK'],
            ['name' => 'Slovenia (+386)', 'country_code' =>'+386' ,'code' => 'SI'],
            ['name' => 'Solomon Islands (+677)', 'country_code' =>'+677' ,'code' => 'SB'],
            ['name' => 'Somalia (+252)','country_code' =>'+252' , 'code' => 'SO'],
            ['name' => 'South Africa (+27)', 'country_code' =>'+27' ,'code' => 'ZA'],
            ['name' => 'South Korea (+82)', 'country_code' =>'+82' ,'code' => 'KR'],
            ['name' => 'South Sudan (+211)','country_code' =>'+211' , 'code' => 'SS'],
            ['name' => 'Spain (+34)', 'country_code' =>'+34' ,'code' => 'ES'],
            ['name' => 'Sri Lanka (+94)', 'country_code' =>'+94' ,'code' => 'LK'],
            ['name' => 'St. Barthélemy (+590)', 'country_code' =>'+590' ,'code' => 'BL'],
            ['name' => 'St. Helena (+290)', 'country_code' =>'+290' ,'code' => 'SH'],
            ['name' => 'St. Kitts &amp; Nevis (+1)', 'country_code' =>'+1' ,'code' => 'KN'],
            ['name' => 'St. Lucia (+1)', 'country_code' =>'+1' ,'code' => 'LC'],
            ['name' => 'St. Martin (+590)', 'country_code' =>'+590' ,'code' => 'MF'],
            ['name' => 'St. Pierre &amp; Miquelon (+508)','country_code' =>'+580' , 'code' => 'PM'],
            ['name' => 'St. Vincent &amp; Grenadines (+1)', 'country_code' =>'+1' ,'code' => 'VC'],
            ['name' => 'Sudan (+249)', 'country_code' =>'+249' ,'code' => 'SD'],
            ['name' => 'Suriname (+597)','country_code' =>'+597' , 'code' => 'SR'],
            ['name' => 'Svalbard &amp; Jan Mayen (+47)', 'country_code' =>'+47' ,'code' => 'SJ'],
            ['name' => 'Sweden (+46)','country_code' =>'+46' , 'code' => 'SE'],
            ['name' => 'Switzerland (+41)','country_code' =>'+41' , 'code' => 'CH'],
            ['name' => 'Syria (+963)', 'country_code' =>'+963' ,'code' => 'SY'],
            ['name' => 'Taiwan (+886)', 'country_code' =>'+886' ,'code' => 'TW'],
            ['name' => 'Tajikistan (+992)','country_code' =>'+992' , 'code' => 'TJ'],
            ['name' => 'Tanzania (+255)','country_code' =>'+255' , 'code' => 'TZ'],
            ['name' => 'Thailand (+66)','country_code' =>'+66' , 'code' => 'TH'],
            ['name' => 'Timor-Leste (+670)', 'country_code' =>'+670' ,'code' => 'TL'],
            ['name' => 'Togo (+228)','country_code' =>'+228' , 'code' => 'TG'],
            ['name' => 'Tokelau (+690)', 'country_code' =>'+690' ,'code' => 'TK'],
            ['name' => 'Tonga (+676)', 'country_code' =>'+676' ,'code' => 'TO'],
            ['name' => 'Trinidad &amp; Tobago (+1)', 'country_code' =>'+1' ,'code' => 'TT'],
            ['name' => 'Tunisia (+216)','country_code' =>'+216' , 'code' => 'TN'],
            ['name' => 'Turkey (+90)','country_code' =>'+90' , 'code' => 'TR'],
            ['name' => 'Turkmenistan (+993)','country_code' =>'+993' , 'code' => 'TM'],
            ['name' => 'Turks &amp; Caicos Islands (+1)', 'country_code' =>'+1' ,'code' => 'TC'],
            ['name' => 'Tuvalu (+688)','country_code' =>'+688' , 'code' => 'TV'],
            ['name' => 'U.S. Virgin Islands (+1)', 'country_code' =>'+1' ,'code' => 'VI'],
            ['name' => 'Uganda (+256)', 'country_code' =>'+256' ,'code' => 'UG'],
            ['name' => 'Ukraine (+380)','country_code' =>'+380' , 'code' => 'UA'],
            ['name' => 'United Arab Emirates (+971)','country_code' =>'+971' , 'code' => 'AE'],
            ['name' => 'United Kingdom (+44)', 'country_code' =>'+44' ,'code' => 'GB'],
            ['name' => 'United States (+1)','country_code' =>'+1' , 'code' => 'US'],
            ['name' => 'Uruguay (+598)','country_code' =>'+598' , 'code' => 'UY'],
            ['name' => 'Uzbekistan (+998)', 'country_code' =>'+998' ,'code' => 'UZ'],
            ['name' => 'Vanuatu (+678)','country_code' =>'+678' , 'code' => 'VU'],
            ['name' => 'Vatican City (+39)','country_code' =>'+39' , 'code' => 'VA'],
            ['name' => 'Venezuela (+58)','country_code' =>'+58' , 'code' => 'VE'],
            ['name' => 'Vietnam (+84)','country_code' =>'+84' , 'code' => 'VN'],
            ['name' => 'Wallis &amp; Futuna (+681)','country_code' =>'+681' , 'code' => 'WF'],
            ['name' => 'Western Sahara (+212)', 'country_code' =>'+212' ,'code' => 'EH'],
            ['name' => 'Yemen (+967)','country_code' =>'+967' , 'code' => 'YE'],
            ['name' => 'Zambia (+260)', 'country_code' =>'+260' ,'code' => 'ZM'],
            ['name' => 'Zimbabwe (+263)','country_code' =>'+263' , 'code' => 'ZW'],
        ];
          
        foreach ($country_codes as $key => $value) {
            CountryCode::create($value);
        }
    
    }
}
