<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CountryCode;

class CountryCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CountryCode::truncate();
  
        $country_codes = [
            ['name' => 'India (+91)', 'code' => 'IN'],
            ['name' => 'Afghanistan (+93)', 'code' => 'AF'],
            ['name' => 'Åland Islands (+358)', 'code' => 'AX'],
            ['name' => 'Albania (+355)', 'code' => 'AL'],
            ['name' => 'Algeria (+213)', 'code' => 'DZ'],
            ['name' => 'American Samoa (+1)', 'code' => 'AS'],
            ['name' => 'Andorra (+376)', 'code' => 'AD'],
            ['name' => 'Angola (+244)', 'code' => 'AO'],
            ['name' => 'Anguilla (+1)', 'code' => 'AI'],
            ['name' => 'Antigua Barbuda (+1)', 'code' => 'AG'],
            ['name' => 'Argentina (+54)', 'code' => 'AR'],
            ['name' => 'Armenia (+374)', 'code' => 'AM'],
            ['name' => 'Aruba (+297)', 'code' => 'AW'],
            ['name' => 'Australia (+61)', 'code' => 'AU'],
            ['name' => 'Austria (+43)', 'code' => 'AT'],
            ['name' => 'Azerbaijan (+994)', 'code' => 'AZ'],
            ['name' => 'Bahamas (+1)', 'code' => 'BS'],
            ['name' => 'Bahrain (+973)', 'code' => 'BH'],
            ['name' => 'Bangladesh (+880)', 'code' => 'BD'],
            ['name' => 'Barbados (+1)', 'code' => 'BB'],
            ['name' => 'Belarus (+375)', 'code' => 'BY'],
            ['name' => 'Belgium (+32)', 'code' => 'BE'],
            ['name' => 'Belize (+501)', 'code' => 'BZ'],
            ['name' => 'Benin (+229)', 'code' => 'BJ'],
            ['name' => 'Bermuda (+1)', 'code' => 'BM'],
            ['name' => 'Bhutan (+975)', 'code' => 'BT'],
            ['name' => 'Bolivia (+591)', 'code' => 'BO'],
            ['name' => 'Bosnia Herzegovina (+387)', 'code' => 'BA'],
            ['name' => 'Botswana (+267)', 'code' => 'BW'],
            ['name' => 'Brazil (+55)', 'code' => 'BR'],
            ['name' => 'British Indian Ocean Territory (+246)', 'code' => 'IO'],
            ['name' => 'British Virgin Islands (+1)', 'code' => 'VG'],
            ['name' => 'Brunei (+673)', 'code' => 'BN'],
            ['name' => 'Bulgaria (+359)', 'code' => 'BG'],
            ['name' => 'Burkina Faso (+226)', 'code' => 'BF'],
            ['name' => 'Burundi (+257)', 'code' => 'BI'],
            ['name' => 'Cambodia (+855)', 'code' => 'KH'],
            ['name' => 'Cameroon (+237)', 'code' => 'CM'],
            ['name' => 'Canada (+1)', 'code' => 'CA'],
            ['name' => 'Cape Verde (+238)', 'code' => 'CV'],
            ['name' => 'Caribbean Netherlands (+599)', 'code' => 'BQ'],
            ['name' => 'Cayman Islands (+1)', 'code' => 'KY'],
            ['name' => 'Central African Republic (+236)', 'code' => 'CF'],
            ['name' => 'Chad (+235)', 'code' => 'TD'],
            ['name' => 'Chile (+56)', 'code' => 'CL'],
            ['name' => 'China (+86)', 'code' => 'CN'],
            ['name' => 'Christmas Island (+61)', 'code' => 'CX'],
            ['name' => 'Cocos (Keeling) Islands (+61)', 'code' => 'CC'],
            ['name' => 'Colombia (+57)', 'code' => 'CO'],
            ['name' => 'Comoros (+269)', 'code' => 'KM'],
            ['name' => 'Congo - Brazzaville (+242)','code' => 'CG'],
            ['name' => 'Congo - Kinshasa (+243)', 'code' => 'CD'],
            ['name' => 'Cook Islands (+682)', 'code' => 'CK'],
            ['name' => 'Costa Rica (+506)', 'code' => 'CR'],
            ['name' => 'Côte d’Ivoire (+225)', 'code' => 'CI'],
            ['name' => 'Croatia (+385)', 'code' => 'HR'],
            ['name' => 'Cuba (+53)', 'code' => 'CU'],
            ['name' => 'Curaçao (+599)', 'code' => 'CW'],
            ['name' => 'Cyprus (+357)', 'code' => 'CY'],
            ['name' => 'Czechia (+420)', 'code' => 'CZ'],
            ['name' => 'Denmark (+45)', 'code' => 'DK'],
            ['name' => 'Djibouti (+253)', 'code' => 'DJ'],
            ['name' => 'Dominica (+1)', 'code' => 'DM'],
            ['name' => 'Dominican Republic (+1)', 'code' => 'DO'],
            ['name' => 'Ecuador (+593)', 'code' => 'EC'],
            ['name' => 'Egypt (+20)', 'code' => 'EG'],
            ['name' => 'El Salvador (+503)', 'code' => 'SV'],
            ['name' => 'Equatorial Guinea (+240)', 'code' => 'GQ'],
            ['name' => 'Eritrea (+291)', 'code' => 'ER'],
            ['name' => 'Estonia (+372)', 'code' => 'EE'],
            ['name' => 'Eswatini (+268)', 'code' => 'SZ'],
            ['name' => 'Ethiopia (+251)', 'code' => 'ET'],
            ['name' => 'Falkland Islands (+500)', 'code' => 'FK'],
            ['name' => 'Faroe Islands (+298)', 'code' => 'FO'],
            ['name' => 'Fiji (+679)', 'code' => 'FJ'],
            ['name' => 'Finland (+358)', 'code' => 'FI'],
            ['name' => 'France (+33)', 'code' => 'FR'],
            ['name' => 'French Guiana (+594)', 'code' => 'GF'],
            ['name' => 'French Polynesia (+689)', 'code' => 'PF'],
            ['name' => 'Gabon (+241)', 'code' => 'GA'],
            ['name' => 'Gambia (+220)', 'code' => 'GM'],
            ['name' =>'Georgia (+995)', 'code' => 'GE'],
            ['name' =>'Germany (+49)', 'code' => 'DE'],
            ['name' =>'Ghana (+233)', 'code' => 'GH'],
            ['name' =>'Gibraltar (+350)', 'code' => 'GI'],
            ['name' =>'Greece (+30)', 'code' => 'GR'],
            ['name' =>'Greenland (+299)', 'code' => 'GL'],
            ['name' =>'Grenada (+1)', 'code' => 'GD'],
            ['name' =>'Guadeloupe (+590)', 'code' => 'GP'],
            ['name' =>'Guam (+1)', 'code' => 'GU'],
            ['name' =>'Guatemala (+502)', 'code' => 'GT'],
            ['name' =>'Guernsey (+44)' , 'code' =>'GG'],
            ['name' =>'Guinea (+224)' , 'code' =>'GN'],
            ['name' =>'Guinea-Bissau (+245)' , 'code' =>'GW'],
            ['name' =>'Guyana (+592)' , 'code' =>'GY'],
            ['name' =>'Haiti (+509)' , 'code' =>'HT'],
            ['name' =>'Honduras (+504)' , 'code' =>'HN'],
            ['name' =>'Hong Kong SAR China (+852)' , 'code' =>'HK'],
            ['name' =>'Hungary (+36)' , 'code' =>'HU'],
            ['name' =>'Iceland (+354)' , 'code' =>'IS'],
            ['name' =>'India (+91)' , 'code' =>'IN'],
            ['name' =>'Indonesia (+62)' , 'code' =>'ID'],
            ['name' =>'Iran (+98)' , 'code' =>'IR'],
            ['name' =>'Iraq (+964)' , 'code' =>'IQ'],
            ['name' =>'Ireland (+353)' , 'code' =>'IE'],
            ['name' =>'Isle of Man (+44)' , 'code' =>'IM'],
            ['name' =>'Israel (+972)' , 'code' => 'IL'],
            ['name' =>'Italy (+39)' , 'code' => 'IT'],
            ['name' =>'Jamaica (+1)' , 'code' => 'JM'],
            ['name' =>'Japan (+81)' , 'code' => 'JP'],
            ['name' =>'Jersey (+44)' , 'code' => 'JE'],
            ['name' =>'Jordan (+962)' , 'code' => 'JO'],
            ['name' =>'Kazakhstan (+7)' , 'code' => 'KZ'],
            ['name' =>'Kenya (+254)' , 'code' => 'KE'],
            ['name' =>'Kiribati (+686)' , 'code' => 'KI'],
            ['name' =>'Kuwait (+965)' , 'code' => 'KW'],
            ['name' =>'Kyrgyzstan (+996)' , 'code' => 'KG'],
            ['name' =>'Laos (+856)' , 'code' => 'LA'],
            ['name' =>'Latvia (+371)' , 'code' => 'LV'],
            ['name' =>'Lebanon (+961)' , 'code' => 'LB'],
            ['name' =>'Lesotho (+266)' , 'code' => 'LS'],
            ['name' =>'Liberia (+231)' , 'code' => 'LR'],
            ['name' => 'Libya (+218)' , 'code' => 'LY'],
            ['name' => 'Liechtenstein (+423)' , 'code' => 'LI'],
            ['name' => 'Lithuania (+370)' , 'code' => 'LT'],
            ['name' => 'Luxembourg (+352)' , 'code' => 'LU'],
            ['name' => 'Macao SAR China (+853)' , 'code' => 'MO'],
            ['name' => 'Madagascar (+261)' , 'code' => 'MG'],
            ['name' => 'Malawi (+265)' , 'code' => 'MW'],
            ['name' => 'Malaysia (+60)' , 'code' => 'MY'],
            ['name' => 'Maldives (+960)' , 'code' => 'MV'],
            ['name' => 'Mali (+223)' , 'code' => 'ML'],
            ['name' => 'Malta (+356)' , 'code' => 'MT'],
            ['name' => 'Marshall Islands (+692)' , 'code' => 'MH'],
            ['name' => 'Martinique (+596)' , 'code' => 'MQ'],
            ['name' => 'Mauritania (+222)' , 'code' => 'MR'],
            ['name' => 'Mauritius (+230)' , 'code' => 'MU'],
            ['name' => 'Mayotte (+262)' , 'code' => 'YT'],
            ['name' => 'Mexico (+52)' , 'code' => 'MX'],
            ['name' => 'Micronesia (+691)' , 'code' => 'FM'],
            ['name' => 'Moldova (+373)' , 'code' => 'MD'],
            ['name' => 'Monaco (+377)' , 'code' => 'MC'],
            ['name' => 'Mongolia (+976)' , 'code' => 'MN'],
            ['name' => 'Montenegro (+382)' , 'code' => 'ME'],
            ['name' => 'Montserrat (+1)' , 'code' => 'MS'],
            ['name' => 'Morocco (+212)' , 'code' => 'MA'],
            ['name' => 'Mozambique (+258)' , 'code' => 'MZ'],
            ['name' => 'Myanmar (Burma) (+95)' , 'code' => 'MM'],
            ['name' => 'Namibia (+264)' , 'code' => 'NA'],
            ['name' => 'Nauru (+674)' , 'code' => 'NR'],
            ['name' => 'Nepal (+977)' , 'code' => 'NP'],
            ['name' => 'Netherlands (+31)' , 'code' => 'NL'],
            ['name' => 'New Caledonia (+687)' , 'code' => 'NC'],
            ['name' => 'New Zealand (+64)' , 'code' => 'NZ'],
            ['name' => 'Nicaragua (+505)' , 'code' => 'NI'],
            ['name' => 'Niger (+227)' , 'code' => 'NE'],
            ['name' => 'Nigeria (+234)' , 'code' => 'NG'],
            ['name' => 'Niue (+683)' , 'code' => 'NU'],
            ['name' => 'Norfolk Island (+672)' , 'code' => 'F'],
            ['name' => 'North Korea (+850)' , 'code' => 'KP'],
            ['name' => 'North Macedonia (+389)' , 'code' => 'MK'],
            ['name' => 'Northern Mariana Islands (+1)' , 'code' => 'MP'],
            ['name' => 'Norway (+47)' , 'code' => 'NO'],
            ['name' => 'Oman (+968)', 'code' => 'OM'],
            ['name' => 'Pakistan (+92)' , 'code' => 'PK'],
            ['name' => 'Palau (+680)' , 'code' => 'PW'],
            ['name' => 'Palestinian Territories (+970)' , 'code' => 'PS'],
            ['name' => 'Panama (+507)' , 'code' => 'PA'],
            ['name' => 'Papua New Guinea (+675)' , 'code' => 'PG'],
            ['name' => 'Paraguay (+595)' , 'code' => 'PY'],
            ['name' => 'Peru (+51)' , 'code' => 'PE'],
            ['name' => 'Philippines (+63)', 'code' => 'PH'],
            ['name' => 'Poland (+48)', 'code' => 'PL'],
            ['name' => 'Portugal (+351)', 'code' => 'PT'],
            ['name' => 'Puerto Rico (+1)', 'code' => 'PR'],
            ['name' => 'Qatar (+974)', 'code' => 'QA'],
            ['name' => 'Réunion (+262)', 'code' => 'RE'],
            ['name' => 'Romania (+40)', 'code' => 'RO'],
            ['name' => 'Russia (+7)', 'code' => 'RU'],
            ['name' => 'Rwanda (+250)', 'code' => 'RW'],
            ['name' => 'Samoa (+685)', 'code' => 'WS'],
            ['name' => 'San Marino (+378)', 'code' => 'SM'],
            ['name' => 'São Tomé &amp; Príncipe (+239)', 'code' => 'ST'],
            ['name' => 'Saudi Arabia (+966)', 'code' => 'SA'],
            ['name' => 'Senegal (+221)', 'code' => 'SN'],
            ['name' => 'Serbia (+381)', 'code' => 'RS'],
            ['name' => 'Seychelles (+248)', 'code' => 'SC'],
            ['name' => 'Sierra Leone (+232)', 'code' => 'SL'],
            ['name' => 'Singapore (+65)', 'code' => 'SG'],
            ['name' => 'Sint Maarten (+1)', 'code' => 'SX'],
            ['name' => 'Slovakia (+421)', 'code' => 'SK'],
            ['name' => 'Slovenia (+386)', 'code' => 'SI'],
            ['name' => 'Solomon Islands (+677)', 'code' => 'SB'],
            ['name' => 'Somalia (+252)', 'code' => 'SO'],
            ['name' => 'South Africa (+27)', 'code' => 'ZA'],
            ['name' => 'South Korea (+82)', 'code' => 'KR'],
            ['name' => 'South Sudan (+211)', 'code' => 'SS'],
            ['name' => 'Spain (+34)', 'code' => 'ES'],
            ['name' => 'Sri Lanka (+94)', 'code' => 'LK'],
            ['name' => 'St. Barthélemy (+590)', 'code' => 'BL'],
            ['name' => 'St. Helena (+290)', 'code' => 'SH'],
            ['name' => 'St. Kitts &amp; Nevis (+1)', 'code' => 'KN'],
            ['name' => 'St. Lucia (+1)', 'code' => 'LC'],
            ['name' => 'St. Martin (+590)', 'code' => 'MF'],
            ['name' => 'St. Pierre &amp; Miquelon (+508)', 'code' => 'PM'],
            ['name' => 'St. Vincent &amp; Grenadines (+1)', 'code' => 'VC'],
            ['name' => 'Sudan (+249)', 'code' => 'SD'],
            ['name' => 'Suriname (+597)', 'code' => 'SR'],
            ['name' => 'Svalbard &amp; Jan Mayen (+47)', 'code' => 'SJ'],
            ['name' => 'Sweden (+46)', 'code' => 'SE'],
            ['name' => 'Switzerland (+41)', 'code' => 'CH'],
            ['name' => 'Syria (+963)', 'code' => 'SY'],
            ['name' => 'Taiwan (+886)', 'code' => 'TW'],
            ['name' => 'Tajikistan (+992)', 'code' => 'TJ'],
            ['name' => 'Tanzania (+255)', 'code' => 'TZ'],
            ['name' => 'Thailand (+66)', 'code' => 'TH'],
            ['name' => 'Timor-Leste (+670)', 'code' => 'TL'],
            ['name' => 'Togo (+228)', 'code' => 'TG'],
            ['name' => 'Tokelau (+690)', 'code' => 'TK'],
            ['name' => 'Tonga (+676)', 'code' => 'TO'],
            ['name' => 'Trinidad &amp; Tobago (+1)', 'code' => 'TT'],
            ['name' => 'Tunisia (+216)', 'code' => 'TN'],
            ['name' => 'Turkey (+90)', 'code' => 'TR'],
            ['name' => 'Turkmenistan (+993)', 'code' => 'TM'],
            ['name' => 'Turks &amp; Caicos Islands (+1)', 'code' => 'TC'],
            ['name' => 'Tuvalu (+688)', 'code' => 'TV'],
            ['name' => 'U.S. Virgin Islands (+1)', 'code' => 'VI'],
            ['name' => 'Uganda (+256)', 'code' => 'UG'],
            ['name' => 'Ukraine (+380)', 'code' => 'UA'],
            ['name' => 'United Arab Emirates (+971)', 'code' => 'AE'],
            ['name' => 'United Kingdom (+44)', 'code' => 'GB'],
            ['name' => 'United States (+1)', 'code' => 'US'],
            ['name' => 'Uruguay (+598)', 'code' => 'UY'],
            ['name' => 'Uzbekistan (+998)', 'code' => 'UZ'],
            ['name' => 'Vanuatu (+678)', 'code' => 'VU'],
            ['name' => 'Vatican City (+39)', 'code' => 'VA'],
            ['name' => 'Venezuela (+58)', 'code' => 'VE'],
            ['name' => 'Vietnam (+84)', 'code' => 'VN'],
            ['name' => 'Wallis &amp; Futuna (+681)', 'code' => 'WF'],
            ['name' => 'Western Sahara (+212)', 'code' => 'EH'],
            ['name' => 'Yemen (+967)', 'code' => 'YE'],
            ['name' => 'Zambia (+260)', 'code' => 'ZM'],
            ['name' => 'Zimbabwe (+263)', 'code' => 'ZW'],
        ];
          
        foreach ($country_codes as $key => $value) {
            CountryCode::create($value);
        }
    
    }
}
